# .github/workflows/azure-deploy.yml
name: Azure Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Set up Node.js for frontend
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Set up Python for backend
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install frontend dependencies and build
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    # Install backend dependencies
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Deploy frontend to Azure Static Web Apps
    - name: Deploy frontend
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/frontend"
        output_location: "build"
        skip_app_build: false

    # Deploy backend to Azure App Service
    - name: Deploy backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend
