name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main, release-prep ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create settings JSON
      run: |
        echo '{
          "WEBSITES_ENABLE_APP_SERVICE_STORAGE": "true",
          "OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}",
          "OPENAI_API_BASE": "${{ secrets.OPENAI_API_BASE }}",
          "OPENAI_API_VERSION": "2023-05-15",
          "OPENAI_DEPLOYMENT_NAME": "${{ secrets.OPENAI_DEPLOYMENT_NAME }}",
          "VECTOR_SEARCH_ENABLED": "${{ secrets.VECTOR_SEARCH_ENABLED }}",
          "VECTOR_SEARCH_ENDPOINT": "${{ secrets.VECTOR_SEARCH_ENDPOINT }}",
          "VECTOR_SEARCH_KEY": "${{ secrets.VECTOR_SEARCH_KEY }}",
          "VECTOR_SEARCH_INDEX": "${{ secrets.VECTOR_SEARCH_INDEX }}",
          "SYSTEM_PROMPT": "${{ secrets.SYSTEM_PROMPT }}"
        }' > appsettings.json

    - name: Configure App Settings
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az webapp config appsettings set \
            --name ${{ secrets.WEBAPP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --settings @appsettings.json

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: backend

    - name: Verify deployment
      run: |
        curl -f https://${{ secrets.WEBAPP_NAME }}.azurewebsites.net/health