name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Initial Setup
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 2. Environment Setup    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 3. Configuration
    - name: Set SCM_DO_BUILD_DURING_DEPLOYMENT
      run: echo "[config]\nSCM_DO_BUILD_DURING_DEPLOYMENT=true" > backend/.deployment

    - name: Configure Always On
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az webapp config set --name ludus-chat-backend \
            --resource-group ludus-chat-rg \
            --always-on true

    - name: Configure App Settings
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az webapp config appsettings set --name ludus-chat-backend \
            --resource-group ludus-chat-rg \
            --settings \
            AZURE_OPENAI_API_KEY="${{ secrets.AZURE_OPENAI_API_KEY }}" \
            AZURE_OPENAI_ENDPOINT="https://ai-trendgpt898002997326.openai.azure.com/" \
            AZURE_OPENAI_DEPLOYMENT_NAME="TrendGPT"

    - name: Create startup command
      run: |
        cd backend
        cat > gunicorn.conf.py << 'EOL'
        import multiprocessing

        bind = "0.0.0.0:8000"
        workers = multiprocessing.cpu_count() * 2 + 1
        worker_class = "uvicorn.workers.UvicornWorker"
        timeout = 120
        keepalive = 5
        wsgi_app = "main:app"
        worker_connections = 1000
        EOL
        echo "gunicorn -c gunicorn.conf.py main:app" > startup.sh
        chmod +x startup.sh

    # 4. Deployment
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ludus-chat-backend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: backend

    - name: Verify deployment
      run: |
        max_attempts=5
        attempt=1
        while [ $attempt -le $max_attempts ]; do
          echo "Attempt $attempt of $max_attempts"
          sleep 30
          if curl -f https://ludus-chat-backend.azurewebsites.net/health; then
            echo "Deployment verified successfully"
            exit 0
          fi
          attempt=$((attempt + 1))
        done
        echo "Deployment verification failed after $max_attempts attempts"
        exit 1
