name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ludus-chat-backend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: backend

    - name: Set SCM_DO_BUILD_DURING_DEPLOYMENT
      run: echo "[config]\nSCM_DO_BUILD_DURING_DEPLOYMENT=true" > backend/.deployment

    - name: Create startup command
      run: |
        cd backend
        echo "gunicorn -c gunicorn.conf.py main:app" > startup.sh
        chmod +x startup.sh

    - name: Configure Always On
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az webapp config set --name ludus-chat-backend \
            --resource-group rg-ryai \
            --always-on true

    - name: Verify deployment
      run: |
        sleep 30
        curl -f https://ludus-chat-backend.azurewebsites.net/health || exit 1
