name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Debug directory structure before
      run: |
        pwd
        ls -la
        ls -la frontend/
        
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build
      run: |
        cd frontend
        npm run build
      env:
        CI: false
        REACT_APP_API_URL: 'https://ludus-chat-backend.azurewebsites.net'
        REACT_APP_WS_URL: 'wss://ludus-chat-backend.azurewebsites.net/ws'
        
    - name: Debug directory structure after build
      run: |
        cd frontend
        ls -la
        ls -la build/
        
    - name: Deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "frontend/build"
        skip_app_build: true
        skip_api_build: true
